# =============================================================================
# YAML Lint Configuration
# =============================================================================
#
# Configuration for yamllint, used by pre-commit hooks.
# Relaxed settings for dotfiles (not as strict as production code).
#
# =============================================================================

extends: relaxed

rules:
  # Allow long lines (common in dotfiles)
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Allow multiple documents in one file
  document-start: disable

  # Consistent indentation
  indentation:
    spaces: 2
    indent-sequences: consistent

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  # Comments
  comments:
    min-spaces-from-content: 1
