---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: true
  document-end:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  hyphens:
    max-spaces-after: 1
  key-duplicates: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  trailing-spaces: enable
